#pragma once

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 3000
#define TAPPING_TERM 200

/* Per-layer RGB tint (H, S, V) — consumed by layer_colors[] in keymap.c */
#define RGB_MATRIX_COLOR_LAYER_0 170, 255, 255
#define RGB_MATRIX_COLOR_LAYER_1 170, 255, 255
#define RGB_MATRIX_COLOR_LAYER_2 0, 255, 255
#define RGB_MATRIX_COLOR_LAYER_3 85, 255, 255
#define RGB_MATRIX_COLOR_LAYER_4 42, 255, 255
#define RGB_MATRIX_COLOR_LAYER_5 127, 255, 255
#define RGB_MATRIX_COLOR_LAYER_6 212, 255, 255

/* No per-key LEDs on this board (underglow only) — keypress-reactive and
 * framebuffer (heatmap/rain) effects are intentionally not enabled. */

/* Trim the animation set to modes that look good on 14 underglow LEDs.
 * The keyboard-level json enables ~30 animations; keeping only these cuts
 * per-frame effect code and firmware size, and shrinks the Vial effect list:
 * SOLID_COLOR (always built in), BREATHING, CYCLE_ALL, CYCLE_LEFT_RIGHT,
 * CYCLE_UP_DOWN, RAINBOW_MOVING_CHEVRON, HUE_WAVE, GRADIENT_LEFT_RIGHT. */
#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef ENABLE_RGB_MATRIX_RAINDROPS

#define VIAL_KEYBOARD_UID {0xA7, 0x90, 0x81, 0x84, 0x11, 0xB1, 0xCB, 0x9D}

#define VIAL_UNLOCK_COMBO_ROWS {0, 1}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define DYNAMIC_KEYMAP_MACRO_COUNT 32

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 8
